fix: let `fd` option be `FileHandle` in `createReadStream`, `createWriteStream`
streamich/memfs pull request #1077
Opened 2024-11-28 00:34 UTC by graue

Letting this option be a `FileHandle` aligns the API with [Node.js's `fs` module](https://nodejs.org/api/fs.html#fscreatewritestreampath-options).

(Split out from #1076 per request)

2024-11-28 18:08 UTC, G-Rath commented on src/__tests__/volume.test.ts
> +  describe('.createWriteStream', () => {
any reason why you've added a test for just `createWriteStream`, but not `createReadStream`?

2024-11-30 04:13 UTC, graue commented on src/__tests__/volume.test.ts
> +  describe('.createWriteStream', () => {
just because they're very similar but sure I can write one for `createReadStream`

2024-12-01 18:12 UTC, G-Rath requested changes
awesome, once you've applied Prettier to the test file, we should be good to go!

2024-12-02 01:30 UTC, G-Rath approved these changes

2024-12-02 01:30 UTC, merged