chore: 🤖 migrate tslint setup to eslint.
streamich/memfs pull request #765
Opened 2021-10-02 21:55 UTC by corwin-of-amber

It seems that `tslint` is deprecated.

https://github.com/palantir/tslint/issues/4534

I have done a "best effort" to create a compatible `eslint` configuration, utilizing `typescript-eslint`, which is supposed to be `tslint`'s direct successor.

There are more disabled rules now, because they were emitting errors on the current code base. Some you may wish to resolve in the code base, then re-enable.

Cheers 👋

2021-10-15 11:46 UTC, corwin-of-amber commented
Should I rebase this?

2022-09-01 22:02 UTC, corwin-of-amber commented
I see work on memfs has renewed lately. I am 100% willing to work on this fix, as well as [this one](https://github.com/corwin-of-amber/memfs/commit/8c4fa0f4f0a7583a3e84e6124d42ee396cf4b088) that allows using `buffer` version 6 (which I'm using so I need this). Just signal if you're available.

2022-10-29 20:07 UTC, G-Rath commented
@corwin-of-amber sorry for the late response - I'm interested in landing this, if you wouldn't mind rebasing :)

2022-10-29 20:10 UTC, G-Rath requested changes

2022-10-29 20:10 UTC, G-Rath commented on eslint.json
> +{
Let's stick this in `.eslintrc.js` as that's more conventional

2024-02-12 20:47 UTC, closed without merging