fix #863 -- realpathSync('/') returns invalid result
streamich/memfs pull request #867
Opened 2022-10-26 01:31 UTC by williamstein

-  https://github.com/streamich/memfs/issues/863

2022-10-29 19:49 UTC, G-Rath requested changes

2022-10-29 19:49 UTC, G-Rath commented on src/__tests__/volume/realpathSync.test.ts
> +describe("edge case -- realpathSync('/') returns '/'", () => {
Similar to [your other PR](https://github.com/streamich/memfs/pull/870#discussion_r1008749448), `describe` isn't a test case - since we've already got a `describe` for `realpathSync` (though I'm not quite sure why we've got a dedicated file for it, but oh well), let's just stick the test in that with a more descriptive title:

```
describe('.realpathSync(...)', () => {
  it('works with symlinks, #463', () => {
    // ...
  });

  it('returns the root correctly', () => {
    // ...
  });
});
```

2022-10-29 19:49 UTC, G-Rath commented on src/volume.ts
> +    return strToEncoding(path ? path : '/', encoding);
we can just use `||` here right?

```suggestion
    return strToEncoding(realLink.getPath() || '/', encoding);
```

2022-10-29 20:04 UTC, G-Rath commented on src/volume.ts
> +    return strToEncoding(path ? path : '/', encoding);
btw fwiw this behavior technically is not correct for Windows, but I think this is still better than the current behaviour so happy to land it

![image](https://user-images.githubusercontent.com/3151613/198850585-e05a3aa1-9949-42fb-91f0-726eb7ced6a1.png)

2022-11-03 16:09 UTC, williamstein commented
OK, I fixed these tests.

2022-11-03 17:41 UTC, G-Rath commented
Awesome! Have you seen [this comment](https://github.com/streamich/memfs/pull/867#discussion_r1008750149)? otherwise this looks good to go

2022-11-04 03:55 UTC, williamstein commented
I saw the comment, but I'm also not sure what to do about it, or what all of the other MS Windows conventions are with memfs, so I don't feel qualified to address it.  I may come back to it later, since Windows support is a longterm goal of my project (https://cowasm.org).

2022-11-04 05:18 UTC, G-Rath commented
I was actually referring to the original comment/suggestion about using `||` to avoid the local variable :)

For the windows comment, thats completely fine though in future I'd recommend putting a reaction such as a thumbs up to indicate you've seen the comment and acknowledge it without any further comment yourself

2022-11-13 18:36 UTC, G-Rath approved these changes

2022-11-13 18:37 UTC, merged

2022-11-13 18:39 UTC, streamich commented
:tada: This PR is included in version 3.4.11 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/memfs/v/3.4.11)
- [GitHub release](https://github.com/streamich/memfs/releases/tag/v3.4.11)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: