fix #558 -- chmodSync throws EISDIR for directories
streamich/memfs pull request #870
Opened 2022-10-26 03:36 UTC by williamstein

- See https://github.com/streamich/memfs/issues/558

The fix for this is similar to the others I just submitting, so here it is.

2022-10-29 19:45 UTC, G-Rath requested changes

2022-10-29 19:45 UTC, G-Rath commented on src/__tests__/volume.test.ts
> +    describe('.chmodSync(directory) works (see https://github.com/streamich/memfs/issues/558', () => {
`describe` blocks are not proper test cases, so this isn't running as you probably expect - let's lay it out like this:

```
describe('.chmodSync(path, mode)', () => {
  it('works with directories', () => {
    // ...
  });

  it('works with files', () => {
    // ...
  });
});
```

and lets put it above the `.promises`, just so its with the rest of the function tests

2022-11-03 15:57 UTC, williamstein commented
I've restructured the tests.

2022-11-03 17:39 UTC, G-Rath approved these changes

2022-11-03 17:40 UTC, merged

2022-11-03 17:41 UTC, streamich commented
:tada: This PR is included in version 3.4.10 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/memfs/v/3.4.10)
- [GitHub release](https://github.com/streamich/memfs/releases/tag/v3.4.10)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: