feat(volume): now handling `Buffer` as volume content
streamich/memfs pull request #880
Opened 2022-11-12 05:27 UTC by shorwood

Hi !

### Content

Quality of life improvement for when you run into cases where you have to inject raw binary date into your volume.

For example when you have binary fixtures you have to inject into your tests.

### Context

While trying inject some `Buffer`s into a `memfs` volume from the `fromJSON` method, I noticed it just created a folder. I expected the method to pass the content to the virtual fileSystem but I then noticed only `string`s are "allowed".

### Actions

I have written a small patch allowing me to fix the issue. I tried to make as few changes as possible.

It comes with a new test closure and some adjustments to the documentation.

I hope it's enough for a quick merge. If not, feel free to share adjustments you would like to be done. I'll try to be as reactive as possible.

Best regards,

Stanley.

2022-11-12 05:54 UTC, G-Rath requested changes

2022-11-12 05:54 UTC, G-Rath commented on src/__tests__/volume.test.ts
> +      it('Files as buffer', () => {
Can you add an `fs.readFile` call to ensure the return from that is valid too?

2022-11-12 05:54 UTC, G-Rath commented on src/__tests__/volume.test.ts
> +        expect(vol.toJSON()).toEqual({
```suggestion
        expect(vol.toJSON()).toStrictEqual({
```

(I know we're not using it in other tests, but we should use it going forward)

2022-11-12 05:54 UTC, G-Rath commented on src/volume.ts
> +type DirectoryContent = string | Buffer | null;
hmm something feels a bit off to me about this change, because it represents both the input and output of `fromJson` and `toJson` respectively yet in your test it looks like giving a Buffer to `fromJson` results in a string when calling `toJson`.

Can you check why that is and if it's the correct behaviour then we'll need to modify the return type of `toJson` to reflect that

2022-11-12 17:36 UTC, shorwood commented on src/volume.ts
> +type DirectoryContent = string | Buffer | null;
I agree, it was off. `toJSON` only returns a map of utf-8 strings.

Here are the changes i've made to resolve the issue:
- Transformed `DirectoryJSON` and `DirectoryNestedJSON` as optionnal generics to allow for type narrowing when needed.
- Changed the return type of `toJSON` and `_toJSON` to reflect the correct behavior.

2022-11-12 17:38 UTC, shorwood commented on src/__tests__/volume.test.ts
> +      it('Files as buffer', () => {
Done :)

2022-11-12 17:40 UTC, shorwood commented on src/__tests__/volume.test.ts
> +        expect(vol.toJSON()).toEqual({
Done.

2022-11-12 20:04 UTC, G-Rath commented on src/volume.ts
> +type DirectoryContent = string | Buffer | null;
> Changed the return type of vol.toJSON and vol._toJSON to reflect the correct behavior:

I don't think that is the correct behaviour for the very reason you want to enable using `Buffer` for `fromJSON` in the first place: binary data cannot be represented as a string - i.e. this will produce an invalid zip:

```
const { Volume } = require('memfs');
const fs = require('fs');

// assume this exists on disk and is a plain zip with one file
const myZip = fs.readFileSync('input.zip');

const vol = new Volume();

vol.fromJSON({ 'my.zip': myZip });

fs.writeFileSync('output.zip', vol.toJSON()['my.zip']);
```

2022-11-13 01:41 UTC, shorwood commented on src/volume.ts
> +type DirectoryContent = string | Buffer | null;
You're right, the changes ignores this case.

I skipped over it because from my point of view (and I might be wrong), `vol.toJSON` is used as debug debug utility, not as an output method. I justify this because the snippet bellow already produces the same invalid zip :

```diff
const { Volume } = require('memfs');
const fs = require('fs');

// assume this exists on disk and is a plain zip with one file
const myZip = fs.readFileSync('input.zip');

const vol = new Volume();

-- vol.fromJSON({ 'my.zip': myZip });
++ vol.writeFileSync('my.zip', myZip);

fs.writeFileSync('output.zip', vol.toJSON()['my.zip']);
```

To me, the zip would be valid if we did:

```diff
const { Volume } = require('memfs');
const fs = require('fs');

// assume this exists on disk and is a plain zip with one file
const myZip = fs.readFileSync('input.zip');

const vol = new Volume();

vol.fromJSON({ 'my.zip': myZip });

-- fs.writeFileSync('output.zip', vol.toJSON()['my.zip']);
++ fs.writeFileSync('output.zip', vol.readFileSync('/my.zip'));
```

## Food for thoughts
But as you pointed out, now that input and output types are not symetrical, this might bring confusion.

One way of reducing this confusion would be to add an optionnal `encoding?: BufferEncoding` parameter to the `vol.toJSON`. Therefore allowing us to explicitly specify the return type of `vol.toJSON`

```ts
vol.toJSON() // { 'file.txt': [Buffer] }
vol.toJSON('utf-8') // { 'file.txt': 'Hello World !' }
```

However, this would bring a breaking change that might have a high impact on existing dependent codebases. One solution to that would be to default `encoding` to `utf-8`. But is the effort worth it and are users going to be using this parameter that ofter ?

## What are your thoughts ?
- Should we assume `vol.toJSON` is just a debug utility and ignore the use case.
- Or should we allow the user to explicitly set the output type of `vol.toJSON`.

2022-11-13 02:06 UTC, shorwood commented on src/volume.ts
> +type DirectoryContent = string | Buffer | null;
To clarify and avoid any misunderstandings:

The return type of `toJSON` is still the same as before: `{ [x: string]: string | null }`

2022-11-13 02:33 UTC, G-Rath commented on src/volume.ts
> +type DirectoryContent = string | Buffer | null;
Good point about `writeFile` - I think the right solution would be something along the lines of that `encoding` parameter (except I'd probably make it a boolean like `asBuffers` since I don't think there's any other options that would make sense); and that means we can land this as-is 🎉

2022-11-13 15:32 UTC, shorwood commented on src/volume.ts
> +type DirectoryContent = string | Buffer | null;
Havent thought of that ! `asBuffer` would be optionnal, fit the need and would not be a breaking change. I'll make the required changes; However, I'm a bit hesitant on where to add this parameter.

Maybe a forth parameter ?

```ts
toJSON(paths?: PathLike | PathLike[], json = {}, isRelative = false, asBuffer = false): DirectoryJSON<string | null>
```

2022-11-13 18:31 UTC, G-Rath commented on src/volume.ts
> +type DirectoryContent = string | Buffer | null;
Cool but lets do it in a new PR because it's easily a separate feature and deserves its own line in the changelog :)

(and yes for now I'd just add a fourth parameter - an `options` object would be better, but overloading is a bit of a hassle and we've not gotten a lot of requests for this so we can improve it later)

2022-11-13 21:46 UTC, shorwood commented on src/volume.ts
> +type DirectoryContent = string | Buffer | null;
Here it is: #881

2023-02-10 23:00 UTC, G-Rath requested changes
You need to apply prettier

2023-02-14 20:51 UTC, shorwood commented on src/__tests__/volume.test.ts
> +      it('Files as buffer', () => {
Resolved: I applied suggested changes.

2023-02-14 20:52 UTC, shorwood commented
> You need to apply prettier

Done.

2023-09-15 22:50 UTC, G-Rath commented
@shorwood are you able to rebase this please?

2023-09-18 20:52 UTC, shorwood commented
> @shorwood are you able to rebase this please?

Hi, it's done. Sorry for the close/reopen, I had to sync and cherry pick because rebase was taking too long on my PC. I have also taken the opportunity to merge the commit from #881 (since they are very similar) and reword them a bit for better understanding.

Awaiting your feedback.

2023-09-18 20:54 UTC, shorwood commented
> @shorwood are you able to rebase this please?

Hi, it's done. Sorry for the close/reopen, I had to sync and cherry pick because rebase was taking too long on my PC. I have also taken the opportunity to merge the commit from #881 (since they are very similar) and reword them a bit for better understanding.

Awaiting your feedback.

2023-09-22 04:46 UTC, G-Rath approved these changes

2023-09-25 19:41 UTC, G-Rath approved these changes

2023-09-25 19:42 UTC, merged

2023-09-25 19:47 UTC, streamich commented
:tada: This PR is included in version 4.5.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/memfs/v/4.5.0)
- [GitHub release](https://github.com/streamich/memfs/releases/tag/v4.5.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: