fix: some metadata changes not follow common unix filesystem lead to node.watchFile not trigger
streamich/memfs pull request #891
Opened 2022-12-21 10:28 UTC by vangie

1. nlink default value is 2
2. add subfolder nlink++
3. atime updated
4. ctime updated after uid/gid/atime/mtime/perm/nlink updated

https://github.com/streamich/memfs/issues/889

2023-02-10 22:57 UTC, G-Rath requested changes

2023-02-10 22:57 UTC, G-Rath commented on src/__tests__/node.test.ts
> +        expect(newCtime !== oldCtime).toBeTruthy();
Let's use `expect` matchers for these checks i.e. `expect(newCtime).not.toBe(oldCtime)`.

2023-02-10 22:57 UTC, G-Rath commented on src/__tests__/promises.test.ts
> +      expect(await promises.readdir('/foo')).toEqual(['.', '..', 'bar', 'baz']);
This behaviour is not correct, per the Node docs:

> Fulfills with an array of the names of the files in the directory excluding '.' and '..'.

Technically it doesn't say that for `readdirSync`, but does do that too:

```
~ via  v16.15.0 via 💎 v3.1.2
❯ mkdir empty

~ via  v16.15.0 via 💎 v3.1.2
❯ node
Welcome to Node.js v16.15.0.
Type ".help" for more information.
> fs.readdirSync('empty')
[]
>
```

2023-03-28 08:12 UTC, vangie commented on src/__tests__/node.test.ts
> +        expect(newCtime !== oldCtime).toBeTruthy();
done

2023-03-28 08:12 UTC, vangie commented on src/__tests__/promises.test.ts
> +      expect(await promises.readdir('/foo')).toEqual(['.', '..', 'bar', 'baz']);
fixed

2023-04-05 19:17 UTC, G-Rath commented
@vangie would you mind applying prettier, then I think we can land this

2023-04-11 03:03 UTC, vangie commented
> @vangie would you mind applying prettier, then I think we can land this

@G-Rath fixed

2023-04-11 04:33 UTC, G-Rath approved these changes

2023-04-11 04:35 UTC, G-Rath commented
@vangie looks like it's still not happy

2023-04-11 11:53 UTC, vangie commented
> @vangie looks like it's still not happy, and the tests are all failing

@G-Rath Sorry, I tried to fix it again. I don’t know why the github action won’t be triggered immediately after I push it.

2023-04-11 19:09 UTC, G-Rath commented on src/node.ts
> +    return new Proxy(this, {
Actually, why are we not using `get` & `set` ers for this? I think that would be better than returning a proxy

2023-04-11 19:10 UTC, G-Rath commented
[It's a security thing](https://github.blog/changelog/2021-04-22-github-actions-maintainers-must-approve-first-time-contributor-workflow-runs/) - you should be able to run the tests locally though to ensure they work.

It looks like this is not compatible with #902 - @alienzhou might be able to help out here

2023-04-11 23:35 UTC, G-Rath commented on src/node.ts
> +    return new Proxy(this, {
hmm I think we should keep things simple by `get` & `set` - Proxy tends to be more complex if things go wrong, and even less performant.

2023-04-11 23:36 UTC, vangie commented on src/node.ts
> +    return new Proxy(this, {
So is there any other suggested way to write it? something like this
```
['prop_1', 'prop_2' ... 'prop_n'].forEach(prop => {
      set [prop](value) {
        this[prop] = value;
      }
});
```

2023-04-11 23:48 UTC, G-Rath commented on src/node.ts
> +    return new Proxy(this, {
No, you just write it as a `get` and `set` in the class:

```
get uid(): number {
  return this._uid;
}

set uid(value: number) {
  this.ctime = new Date();
  this._uid = value;
}

// .. and so on for each property
```

2023-04-11 23:58 UTC, vangie commented on src/node.ts
> +    return new Proxy(this, {
OK

2023-04-12 00:06 UTC, vangie commented on src/node.ts
> +    return new Proxy(this, {
@G-Rath fixed

2023-04-15 22:48 UTC, G-Rath commented on src/node.ts
> +  _uid: number = getuid();
Could you add the appropriate modifiers to these properties + your new getters & setters?

2023-04-15 22:52 UTC, G-Rath commented on src/__tests__/node.test.ts
> +    describe.each([['uid'], ['gid'], ['atime'], ['mtime'], ['perm'], ['nlink']])('ctime changes', field => {
You don't need these nested arrays:

```suggestion
    describe.each(['uid', 'gid', 'atime', 'mtime', 'perm', 'nlink'])('ctime changes', field => {
```

2023-04-15 23:01 UTC, G-Rath requested changes
Looking good - just have a few tweaks I'd like to the test structure

2023-04-15 23:01 UTC, G-Rath commented on src/__tests__/node.test.ts
> +      it(`${method}()`, () => {
Since this doesn't use `field`, let's pull it up a level and change the title to be `when %s is called -> it updates the atime and ctime`

2023-04-16 02:08 UTC, vangie commented on src/node.ts
> +  _uid: number = getuid();
done

2023-04-16 02:18 UTC, vangie commented on src/__tests__/node.test.ts
> +      it(`${method}()`, () => {
I have changed like this
```
    describe.each([
      ['getString', []],
      ['getBuffer', []],
      ['read', [Buffer.alloc(0)]],
    ])('when %s is called', (method, args) => {
      it(`updates the atime and ctime`, () => {
...
```

the `read` method cannot without the `Buffer` argument.

2023-04-16 02:18 UTC, vangie commented on src/__tests__/node.test.ts
> +      it(`set ${field}`, () => {
done

2023-04-16 03:01 UTC, G-Rath commented on src/__tests__/node.test.ts
> +      it(`${method}()`, () => {
I'm not sure what you mean - to be clear by "pull it up a level" I mean do this:

```
describe.each(['uid', 'gid', 'atime', 'mtime', 'perm', 'nlink'])('when %s changes', field => {
 // ...
});

describe.each([
   ['getString', []],
   ['getBuffer', []],
   ['read', [Buffer.alloc(0)]],
 ])('when %s is called', (method, args) => {
   it(`updates the atime and ctime`, () => {
    // ...
  });
});
```

Personally I'm not the biggest fan of using the `describe.each` like this, but it's not the end of the world so if it works it works 🤷

2023-04-17 01:13 UTC, vangie commented on src/__tests__/node.test.ts
> +      it(`${method}()`, () => {
Pull it up a level like this，I have try but if I remove the `read` method's argument `Buffer.alloc(0)`, the test cannot pass. So I don't know how to pull it up without removing `Buffer.alloc`
```
describe.each(['getString', 'getBuffer',  'read'])('when %s is called', method => {
   it(`updates the atime and ctime`, () => {
    // ...
  });
});
```

2023-04-17 01:17 UTC, G-Rath commented on src/__tests__/node.test.ts
> +      it(`${method}()`, () => {
But why are you removing `Buffer.alloc(0)` at all? You shouldn't need to do that to pull it up

2023-04-17 02:57 UTC, vangie commented on src/__tests__/node.test.ts
> +      it(`${method}()`, () => {
So how to get rid of `Buffer.alloc(0)`? Modify the `read` method, such as giving a default value. Or write a test for `read` alone instead of putting it in `describe.each`.

2023-04-17 05:19 UTC, G-Rath commented on src/__tests__/node.test.ts
> +      it(`${method}()`, () => {
I'm not asking you to remove it, so you don't do anything with it 🙂

2023-04-17 07:11 UTC, vangie commented on src/__tests__/node.test.ts
> +      it(`${method}()`, () => {
OK，I tried to change it, if you think it is inappropriate, please give more specific suggestions for modification

2023-04-17 20:27 UTC, G-Rath requested changes

2023-04-17 20:27 UTC, G-Rath commented on src/__tests__/node.test.ts
> +    it('when node.read is called, updates the atime and ctime', () => {
we've already got a `describe` for tests of `.read`, so can you move this under that? (and remove the `when ... called,` )

2023-04-17 20:27 UTC, G-Rath commented on src/__tests__/node.test.ts
> +    describe.each(['getString', 'getBuffer'])('when node.%s is called', method => {
I don't think its worth having an each for two methods like this - instead could you lay it out like this:

```
describe('.getString()', () => {
  it('updates the atime and ctime', () => {
    // ...
  });
});

describe('.getBuffer()', () => {
  it('updates the atime and ctime', () => {
    // ...
  });
});
```

This'll make it easier to add some more tests for those methods in future too.

2023-04-18 01:27 UTC, vangie commented on src/__tests__/node.test.ts
> +    it('when node.read is called, updates the atime and ctime', () => {
OK

2023-04-18 01:27 UTC, vangie commented on src/__tests__/node.test.ts
> +    describe.each(['getString', 'getBuffer'])('when node.%s is called', method => {
done

2023-04-18 04:43 UTC, G-Rath commented on src/__tests__/node.test.ts
> +    describe('.read()', () => {
we've already got a `describe('.read(buf, off, len, pos)', ...` above on line 55 - could you move this test into that?

2023-04-18 07:59 UTC, vangie commented on src/__tests__/node.test.ts
> +    describe('.read()', () => {
done

2023-04-20 19:47 UTC, merged

2023-04-20 19:48 UTC, streamich commented
:tada: This PR is included in version 3.5.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/memfs/v/3.5.1)
- [GitHub release](https://github.com/streamich/memfs/releases/tag/v3.5.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: