Webfs
streamich/memfs pull request #910
Opened 2023-06-14 18:47 UTC by streamich

2023-06-14 21:28 UTC, streamich commented on tsconfig.json
> +    "target": "es6",
This is needed to inherit from `WritableStream`, it is probably still possible to do it some other way. But I think we wanted to switch to es6 some time ago anyways.

2023-06-15 18:34 UTC, G-Rath commented on tsconfig.json
> +    "target": "es6",
Since this is a breaking change, I think we should create a `next` branch and land this change in its own PR to that - the new GitHub release workflow (which we've not yet switched to) supports doing prereleases so that'll let us test the release too.

Assuming you've setup the npm release token like you have for other repos, you just need to disable circleci so it won't try and do a double release when we merge to `master`

2023-06-15 19:17 UTC, G-Rath requested changes
This looks very cool! I've got some small changes I'd like to see (the main one is renaming the `maybe` utility), but nothing major.

2023-06-15 19:17 UTC, G-Rath commented on src/node-to-fsa/__tests__/NodeFileSystemDirectoryHandle.test.ts
> +      expect(await keys.next()).toEqual({ done: true, value: undefined });
nit: ideally we should be using `toStrictEqual`

2023-06-15 19:17 UTC, G-Rath commented on src/node-to-fsa/__tests__/NodeFileSystemDirectoryHandle.test.ts
> +      expect(list.length).toBe(2);
```suggestion
      expect(list).toHaveLength(2);
```

2023-06-15 19:17 UTC, G-Rath commented on src/node-to-fsa/__tests__/NodeFileSystemDirectoryHandle.test.ts
> +      expect(await keys.next()).toEqual({ done: true, value: undefined });
nit: using `await expect(...).resolves` gives some nicer output if the test fails:

```suggestion
      await expect(keys.next()).resolves.toStrictEqual({ done: true, value: undefined });
```

2023-06-15 19:17 UTC, G-Rath commented on src/node-to-fsa/__tests__/NodeFileSystemDirectoryHandle.test.ts
> +      expect(handles.length).toBe(2);
```suggestion
      expect(handles).toHaveLength(2);
```

2023-06-15 19:17 UTC, G-Rath commented on src/node-to-fsa/__tests__/NodeFileSystemDirectoryHandle.test.ts
> +      expect(await values.next()).toEqual({ done: true, value: undefined });
nit: using `await expect(...).resolves` gives some nicer output if the test fails:

```suggestion
      await expect(values.next()).resolves.toStrictEqual({ done: true, value: undefined });
```

2023-06-15 19:17 UTC, G-Rath commented on src/node-to-fsa/__tests__/NodeFileSystemDirectoryHandle.test.ts
> +      expect(handles.length).toBe(2);
```suggestion
      expect(handles).toHaveLength(2);
```

2023-06-15 19:17 UTC, G-Rath commented on src/node-to-fsa/__tests__/NodeFileSystemDirectoryHandle.test.ts
> +      } catch (error) {
You should be able to use the `toThrow` matcher to handle these error tests nicer - i.e. `await expect(...).rejects.toThrow(new DOMException('<message>', '<name'>))`.

Among other things, Jest will fail the test if no error is thrown

2023-06-15 19:17 UTC, G-Rath commented on src/node-to-fsa/__tests__/scenarios.test.ts
> +    expect(await shoppingList.text()).toBe('Milk, Eggs, Bread');
```suggestion
    await expect(shoppingList.text()).resolves.toBe('Milk, Eggs, Bread');
```

2023-06-15 19:17 UTC, G-Rath commented on src/node-to-fsa/__tests__/util.ts
> +export const maybe = nodeMajorVersion >= 20 ? describe : describe.skip;
I think it would be better to call this something like `onlyOnNode20` so its clear under what condition the tests should run.

2023-06-15 19:17 UTC, G-Rath commented on src/node-to-fsa/__tests__/NodeFileSystemFileHandle.test.ts
> +        expect(fs.readFileSync('/file.txt').length).toBe(10);
```suggestion
        expect(fs.readFileSync('/file.txt')).toHaveLength(10);
```

2023-06-15 19:55 UTC, streamich commented on src/node-to-fsa/__tests__/NodeFileSystemDirectoryHandle.test.ts
> +      } catch (error) {
Yes, I know, but I don't like to rely too much on library specific (Jest in this case) assertions if that can be easily done with just code.

2023-06-15 19:56 UTC, streamich commented on src/node-to-fsa/__tests__/scenarios.test.ts
> +    expect(await shoppingList.text()).toBe('Milk, Eggs, Bread');
Yes, I know, but I don't like to rely too much on library specific (Jest in this case) assertions if that can be easily done with just code.

2023-06-15 19:56 UTC, streamich commented on src/node-to-fsa/__tests__/NodeFileSystemDirectoryHandle.test.ts
> +      expect(handles.length).toBe(2);
Yes, I know, but I don't like to rely too much on library specific (Jest in this case) assertions if that can be easily done with just code.

2023-06-15 19:56 UTC, streamich commented on src/node-to-fsa/__tests__/NodeFileSystemDirectoryHandle.test.ts
> +      expect(await values.next()).toEqual({ done: true, value: undefined });
Yes, I know, but I don't like to rely too much on library specific (Jest in this case) assertions if that can be easily done with just code.

2023-06-15 19:56 UTC, streamich commented on src/node-to-fsa/__tests__/NodeFileSystemDirectoryHandle.test.ts
> +      expect(handles.length).toBe(2);
Yes, I know, but I don't like to rely too much on library specific (Jest in this case) assertions if that can be easily done with just code.

2023-06-15 19:56 UTC, streamich commented on src/node-to-fsa/__tests__/NodeFileSystemDirectoryHandle.test.ts
> +      expect(await keys.next()).toEqual({ done: true, value: undefined });
Yes, I know, but I don't like to rely too much on library specific (Jest in this case) assertions if that can be easily done with just code.

2023-06-15 20:00 UTC, streamich commented on src/node-to-fsa/__tests__/NodeFileSystemFileHandle.test.ts
> +        expect(fs.readFileSync('/file.txt').length).toBe(10);
Yes, I know, but I don't like to rely too much on library specific (Jest in this case) assertions if that can be easily done with just code.

2023-06-15 20:08 UTC, streamich commented on src/node-to-fsa/__tests__/util.ts
> +export const maybe = nodeMajorVersion >= 20 ? describe : describe.skip;
Done.

2023-06-15 20:11 UTC, streamich commented
Thanks you @G-Rath for the review! I've addressed your changes and added two more commits which further improve FSA (types and read/write mode). I'll create the `next` branch, with just build/CI/fixes changes, so we can use that to release v4 and test the new workflow.

2023-06-15 20:46 UTC, G-Rath commented
Awesome, sounds like a plan

2023-06-16 16:35 UTC, closed without merging